/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/cube.glb
*/

// import React, { useRef } from 'react'
import { Decal, useGLTF, useTexture } from "@react-three/drei";

export function Cube(props) {
  const { nodes, materials } = useGLTF("/cube.glb");
  const fabric = useTexture({
    map: "/body_Base_Color-min.jpg",
  });
  const logoTexture = useTexture("/bucks.png");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        // material={materials.Material}
      >
        <meshStandardMaterial {...fabric} />
        <Decal
          position={[-1, 0, 0]}
          rotation={Math.PI * 2}
          scale={2}
          map={logoTexture}
          depthTest={true}
          depthWrite={false}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/cube.glb");
// export default Model;
