[[redirects]]
from = "/*"
to = "index.html"
status = 200

[build]
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "false"

[build.production.environment]
  GENERATE_SOURCEMAP = "false"