/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/gltf/NikeMark/NikeFiber.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/NikeFiber.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.NikeFiber_1.geometry} material={materials.bodyTex} />
        <mesh geometry={nodes.NikeFiber_2.geometry} material={materials.soleTex} />
        <mesh geometry={nodes.NikeFiber_3.geometry} material={materials.logo} />
      </group>
    </group>
  )
}

useGLTF.preload('/NikeFiber.gltf')
