/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/Nike3D.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Nike3D.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.New_object_1.geometry} material={materials.soleTexture} />
        <mesh geometry={nodes.New_object_2.geometry} material={materials.bodyTexture} />
      </group>
    </group>
  )
}

useGLTF.preload('/Nike3D.glb')
