/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/icons.gltf
*/

import { useState } from "react";
import { Text3D, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { easing } from "maath";
import { useRef } from "react";
import { state } from "../store";
import { useSnapshot } from "valtio";
import { motion } from "framer-motion-3d";
import * as THREE from "three";

// import bold from "../";

export function Icons({ color, id, price }) {
  const { nodes } = useGLTF("/iconss.gltf");
  const snap = useSnapshot(state);
  const [scale, setScale] = useState(1);
  const cart = useRef();
  const heart = useRef();

  useFrame((state, delta) => {
    // console.log(scale);

    easing.dampC(heart.current.material.color, color, 0.25, delta);
    easing.dampC(cart.current.material.color, snap.cartColor, 0.25, delta);
    easing.dampE(cart.current.scale, [scale, scale, scale], 0.05, delta);
  });
  return (
    <group
      // rotation={[0, -Math.PI / 2, 0]}
      // position={[-1.23, 0.4, 0]}
      rotation={[0, 0, 0]}
      position={[0, -0.3, 0]}
    >
      <motion.mesh
        geometry={nodes.heartcart_1.geometry}
        onClick={() => {
          setScale(1.1);
          setTimeout(() => {
            setScale(1);
          }, [50]);
        }}

        // onClick={() => console.log("clicked")}
      >
        <meshStandardMaterial
          attach="material"
          color={"lime"}
          blending={THREE.AdditiveBlending}
          roughness={1}
          opacity={0.2}
          envMapIntensity={2}
          transparent
          depthWrite={false}
        />
      </motion.mesh>
      <motion.mesh
        ref={cart}
        geometry={nodes.heartcart_3.geometry}
        onClick={() => {
          setScale(1.1);
          setTimeout(() => {
            setScale(1);
          }, [50]);
        }}
      >
        <meshStandardMaterial />
      </motion.mesh>

      <motion.mesh
        ref={heart}
        geometry={nodes.heartcart_4.geometry}
        whileTap={{ scale: 1.1 }}
        onTap={() => {
          state.isClicked[id] = !state.isClicked[id];
        }}
        // onTap={() => {
        //   setIsClicked((prev) => !prev);
        // }}

        // onTap={() => {
        //   snap.heartColor === "black"
        //     ? (state.heartColor = "red")
        //     : (state.heartColor = "black");
        // }}
      >
        <meshStandardMaterial />
      </motion.mesh>

      <mesh position={[0, -0.4, -1.2]} rotation={[0, Math.PI / 2, 0]}>
        <boxGeometry args={[0.5, 1, 0.05]} />
        <meshStandardMaterial
          attach="material"
          color={"lime"}
          blending={THREE.AdditiveBlending}
          roughness={0.2}
          opacity={0.8}
          envMapIntensity={2}
          transparent
        />
      </mesh>

      <Text3D
        size={0.12}
        scale-z={0.2}
        curveSegments={32}
        bevelEnabled
        bevelSize={0.006}
        bevelThickness={0.06}
        rotation-x={[-Math.PI / 2]}
        rotation-y={[-Math.PI / 2]}
        position-z={-0.9}
        position-y={-0.8}
        font={"../../fonts/inter_Bold.json"}
      >
        {price}
        {/* <meshNormalMaterial /> */}
        <meshPhysicalMaterial color={"orange"} />
      </Text3D>
    </group>
  );
}

useGLTF.preload("/iconss.gltf");
