/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/Nikegltf.glb
*/
import { Decal, useGLTF, useTexture } from "@react-three/drei";
// import { useInView } from "react-intersection-observer";

import * as THREE from "three";
import { Icons } from "./Icons";

export function Model() {
  const { nodes, materials } = useGLTF("/gltf/NikeFiber2/NikeFiber.gltf");

  const logoTexture = useTexture("/bucks.png");

  const fabric = useTexture({
    map: "/body_Base_Color-min.jpg",
    // normalMap: "/Nikebody/body_Normal_DirectX.jpg",
    // roughnessMap: "/Nikebody/body_Roughness.jpg",
    // aoMap: "/Nikebody/body_Mixed_AO.jpg",
    // metalnessMap: "/Nikebody/body_Metallic.jpg",
  });

  // fabric.map.wrapS = fabric.map.wrapT = THREE.RepeatWrapping;
  // fabric.map.repeat.set(1, 1);
  // const soleMat = useTexture({
  //   map: "/Nikesole/1001_Base_Color.jpg",
  //   normalMap: "/Nikesole/1001_Normal_DirectX.jpg",
  //   roughnessMap: "/Nikesole/1001_Roughness.jpg",
  //   aoMap: "/Nikesole/1001_Mixed_AO.jpg",
  // });

  return (
    <group rotation={[-Math.PI / 2, Math.PI, Math.PI / 2]}>
      <mesh
        geometry={nodes.NikeFiber_1.geometry}
        material={materials.bodyTex}
        castShadow
        receiveShadow
      ></mesh>
      <mesh
        geometry={nodes.NikeFiber_2.geometry}
        material={materials.soleTex}
        castShadow
        receiveShadow
      />
      <mesh position={[0, -0.5, -1.2]} rotation={[0, Math.PI / 2, 0]}>
        <boxGeometry args={[0.5, 1, 0.05]} />
        <meshStandardMaterial
          attach="material"
          color={"lime"}
          blending={THREE.AdditiveBlending}
          roughness={0.2}
          opacity={0.8}
          envMapIntensity={2}
          transparent
        />
        <Icons />
      </mesh>
    </group>
  );
}

useGLTF.preload("/NikeFiber.gltf");

export default Model;
