/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/Nikegltf.glb
*/
import { Decal, useGLTF, useTexture } from "@react-three/drei";
// import { useInView } from "react-intersection-observer";

import * as THREE from "three";
import { Icons } from "./Icons";

const Nike2 = () => {
  const { nodes, materials } = useGLTF("/gltf/NikeFiber2/NikeFiber.gltf");

  const logoTexture = useTexture("/bucks.png");

  return (
    <group rotation={[-Math.PI / 2, Math.PI, Math.PI / 2]}>
      <mesh
        geometry={nodes.NikeFiber_1.geometry}
        material={materials.bodyTex}
        castShadow
        receiveShadow
      ></mesh>
      <mesh
        geometry={nodes.NikeFiber_2.geometry}
        material={materials.soleTex}
        castShadow
        receiveShadow
      />
      <mesh geometry={nodes.NikeFiber_3.geometry} material={materials.logo} />
      <mesh position={[0, -0.5, -1.2]} rotation={[0, Math.PI / 2, 0]}>
        <boxGeometry args={[0.5, 1, 0.05]} />
        <meshStandardMaterial
          attach="material"
          color={"lime"}
          blending={THREE.AdditiveBlending}
          roughness={0.2}
          opacity={0.8}
          envMapIntensity={2}
          transparent
        />
        <Icons />
      </mesh>
    </group>
  );
};

useGLTF.preload("/gltf/NikeFiber2/NikeFiber.gltf");

export default Nike2;
